test:
	python ./bad_loglog.py
	python ./bloom_filter.py
	python ./countminsketch.py
	python ./crc.py
	python ./hashlist.py
	python ./reservoir_sampling.py
	python ./strstr.py
	python ./levenshtein_distance.py
	python ./bktree.py
	python ./huffman_coding.py
	python ./josephus_problem.py
	python ./expsearch.py
	python ./rope.py
	python ./celebrity_search.py
	python ./gauss_jordan_elimination.py
	python ./nqueens.py
	python ./reconstruct.py
	python ./pancake_flip.py
	python ./bitmap_intset.py
	python ./power2breakdown.py
